language: python
sudo: required
services:
  - docker

env:
  - TOXENV=flake8
  - TOXENV=pylint
  - TOXENV=pytest

install: |
  docker pull starcraftman/new-awesome

script: |
  docker run -e "TOXENV=$TOXENV" -v $(pwd):/project starcraftman/new-awesome bash -c "cd /project && tox"
